---
name: Traceable AST Action
description: "GitHub action for Traceable Active Security Testing"
branding:
  icon: 'activity'
  color: 'red'
inputs:
  step_name:
    required: true
    description: ''
    default: 'NULL'
  scan_name:
    required: false
    description: ''
    default: 'NULL'
  client_scan_token:
    required: true
    description: ''
    default: 'NULL'
  traceable_cli_download_path:
    required: false
    description: ''
    default: 'NULL'
  cli_version:
    required: false
    description: ''
    default: 'latest'
  traffic_env:
    required: true
    description: ''
    default: 'NULL'
  plugins:
    required: false
    description: ''
    default: 'NULL'
  policy:
    required: false
    description: ''
    default: 'NULL'
  include_url_regex:
    required: false
    description: ''
    default: 'NULL'
  exclude_url_regex:
    required: false
    description: ''
    default: 'NULL'
  include_endpoint_labels:
    required: false
    description: ''
    default: 'NULL'
  exclude_endpoint_labels:
    required: false
    description: ''
    default: 'NULL'
  include_endpoint_with_owner_attributes:
    required: false
    description: 'Comma seperted owner attributes'
    default: 'NULL'
  include_endpoint_owners:
    required: false
    description: 'Comma seperated owner values , provided only when include owner attributes are provided'
    default: 'NULL'
  postman_collection:
    required: false
    description: ''
    default: 'NULL'
  postman_environment:
    required: false
    description: ''
    default: 'NULL'
  openapi_spec_ids:
    required: false
    description: 'provide comma separated open api spec ids'
    default: 'NULL'
  openapi_spec_files:
    required: false
    description: 'comma separated files of open api spec documents'
    default: 'NULL'
  target_url:
    required: false
    description: ''
    default: 'NULL'
  traceable_server:
    required: false
    description: ''
    default: 'NULL'
  idle_timeout:
    required: false
    description: ''
    default: '10'
  scan_timeout:
    required: false
    description: ''
    default: 'NULL'
  max_retries:
    required: false
    description: ''
    default: 'NULL'
  log_level:
    required: false
    description: ''
    default: 'NULL'
  traceable_root_ca:
    required: false
    description: ''
    default: 'NULL'
  traceable_cli_cert:
    required: false
    description: ''
    default: 'NULL'
  traceable_cli_key:
    required: false
    description: ''
    default: 'NULL'
  proxy_mode:
    required: false
    description: 'Run a scan in proxy mode or not'
    default: 'false'
  ta_service_name:
    required: false
    description: 'TA service name'
    default: 'proxy'
  tpa_endpoint:
    required: false
    description: 'Traceable platform agent (TPA) reporting endpoint'
    default: 'localhost'

runs:
  using: composite
  steps:
    - name: Validate required parameters
      run: |
        [[ "${{ inputs.step_name }}" != "NULL" ]] || { echo "step name input is empty" ; exit 1; }
        [[ "${{ inputs.client_scan_token }}" != "NULL" ]] || { echo "client_scan_token input is empty" ; exit 1; }
      shell: bash
    - name: Download CLI
      if: ${{ inputs.step_name == 'init' || inputs.step_name == 'init and run' }}
      run: |
        if [[ "${{ inputs.traceable_cli_download_path }}" != "NULL" ]]
        then
          curl -Lo traceableCli.tar.gz ${{ inputs.traceable_cli_download_path }}
          tar -xvf traceableCli.tar.gz --directory ${GITHUB_WORKSPACE}
        else
          if [[ "${{ inputs.cli_version }}"  = *"-rc."* ]]
          then
            curl -OL https://downloads.traceable.ai/cli/rc/${{ inputs.cli_version }}/traceable-cli-${{ inputs.cli_version }}-linux-x86_64.tar.gz
          else
            curl -OL https://downloads.traceable.ai/cli/release/${{ inputs.cli_version }}/traceable-cli-${{ inputs.cli_version }}-linux-x86_64.tar.gz
          fi
          tar -xvf ${GITHUB_WORKSPACE}/traceable-cli-${{ inputs.cli_version }}-linux-x86_64.tar.gz --directory ${GITHUB_WORKSPACE}
        fi
      shell: bash
    - name: Init and run command on cli
      if: ${{ inputs.step_name == 'init and run' }}
      run: |
        export LC_ALL=en_US.utf-8
        export LANG=en_US.utf-8
        
        if  [[ -n "${{ inputs.traceable_root_ca }}" ]] && [[ "${{ inputs.traceable_root_ca }}" != "''" ]] && [[ "${{ inputs.traceable_root_ca }}" != "NULL" ]]
        then
          echo "${{ inputs.traceable_root_ca }}" > /tmp/ca_file.crt
          export TRACEABLE_ROOT_CA_FILE_NAME=/tmp/ca_file.crt
        fi
        if  [[ -n "${{ inputs.traceable_cli_cert }}" ]] && [[ "${{ inputs.traceable_cli_cert }}" != "''" ]] && [[ "${{ inputs.traceable_cli_cert }}" != "NULL" ]]
        then
          echo "${{ inputs.traceable_cli_cert }}" > /tmp/ca_cert.crt
          export TRACEABLE_CLI_CERT_FILE_NAME=/tmp/ca_cert.crt
        fi
        if  [[ -n "${{ inputs.traceable_cli_key }}" ]] && [[ "${{ inputs.traceable_cli_key }}" != "''" ]] && [[ "${{ inputs.traceable_cli_key }}" != "NULL" ]]
        then
          echo "${{ inputs.traceable_cli_key }}" > /tmp/ca_key.crt
          export TRACEABLE_CLI_KEY_FILE_NAME=/tmp/ca_key.crt
        fi
        
        traceableCliBinaryLocation=${GITHUB_WORKSPACE}/traceable
        
        scanInitCmd=$traceableCliBinaryLocation' ast scan initAndRun'
        optionsArr=('--scan-name' '--traffic-env' '--token' '--plugins' '--include-url-regex' '--exclude-url-regex' '--target-url' '--traceable-server' '--idle-timeout' '--scan-timeout' ' --reference-env' '--max-retries' '--openapi-spec-ids' '--openapi-spec-files' '--policy' '--postman-collection' '--postman-environment' '--include-endpoint-labels' '--exclude-endpoint-labels' '--include-endpoint-with-owner-attributes' '--include-endpoint-owners' '--loglevel')
        
        #Iterating the options available from options array and filling them with the arguments received in order
        iterator=0
        for option in '${{ inputs.scan_name }}' '${{ inputs.traffic_env }}' '${{ inputs.client_scan_token }}' '${{ inputs.plugins }}' '"${{ inputs.include_url_regex }}"' '"${{ inputs.exclude_url_regex }}"' '${{ inputs.target_url }}' '${{ inputs.traceable_server }}' '${{ inputs.idle_timeout }}' '${{ inputs.scan_timeout }}' '${{ inputs.reference_env }}' '${{ inputs.max_retries }}' '${{ inputs.openapi_spec_ids }}' '${{ inputs.openapi_spec_files }}' '${{ inputs.policy }}' '${{ inputs.postman_collection }}' '${{ inputs.postman_environment }}' '${{ inputs.include_endpoint_labels}}' '${{ inputs.exclude_endpoint_labels }}' '${{ inputs.include_endpoint_with_owner_attributes }}' '${{ inputs.include_endpoint_owners }}' '${{ inputs.log_level }}'
        do
          if [ -z "$option" ] || [ "$option" = "''" ] || [ "$option" = "NULL" ]
          then
            echo "${optionsArr[$iterator]}" is Null
          else
            scanInitCmd=$scanInitCmd"  "${optionsArr[$iterator]}" "${option}
          fi
          iterator=$(($iterator+1))
        done
        
        if [[ "${{ inputs.proxy_mode }}" == "true" ]]
        then
          export TRACEABLE_PROXY_HOST=localhost
          export TRACEABLE_PROXY_PORT=18080
          export TA_SERVICE_NAME="${{ inputs.ta_service_name }}"
          unset http_proxy
          scanInitCmd=$scanInitCmd" -tpa "${{ inputs.tpa_endpoint }}" --proxy"
        fi

        $scanInitCmd

      shell: bash
    - name: Init command on cli
      if: ${{ inputs.step_name == 'init' }}
      run: |
        export LC_ALL=en_US.utf-8
        export LANG=en_US.utf-8
        
        if  [[ -n "${{ inputs.traceable_root_ca }}" ]] && [[ "${{ inputs.traceable_root_ca }}" != "''" ]] && [[ "${{ inputs.traceable_root_ca }}" != "NULL" ]]
        then
          echo "${{ inputs.traceable_root_ca }}" > /tmp/ca_file.crt
          export TRACEABLE_ROOT_CA_FILE_NAME=/tmp/ca_file.crt
        fi
        if  [[ -n "${{ inputs.traceable_cli_cert }}" ]] && [[ "${{ inputs.traceable_cli_cert }}" != "''" ]] && [[ "${{ inputs.traceable_cli_cert }}" != "NULL" ]]
        then
          echo "${{ inputs.traceable_cli_cert }}" > /tmp/ca_cert.crt
          export TRACEABLE_CLI_CERT_FILE_NAME=/tmp/ca_cert.crt
        fi
        if  [[ -n "${{ inputs.traceable_cli_key }}" ]] && [[ "${{ inputs.traceable_cli_key }}" != "''" ]] && [[ "${{ inputs.traceable_cli_key }}" != "NULL" ]]
        then
          echo "${{ inputs.traceable_cli_key }}" > /tmp/ca_key.crt
          export TRACEABLE_CLI_KEY_FILE_NAME=/tmp/ca_key.crt
        fi
        
        traceableCliBinaryLocation=${GITHUB_WORKSPACE}/traceable
        
        scanInitCmd=$traceableCliBinaryLocation' ast scan init '
        optionsArr=('--scan-name' '--traffic-env' '--token' '--plugins' '--include-url-regex' '--exclude-url-regex' '--target-url' '--traceable-server'  '--scan-timeout' ' --reference-env' '--openapi-spec-ids' '--openapi-spec-files' '--policy' '--include-endpoint-labels' '--exclude-endpoint-labels' '--include-endpoint-with-owner-attributes' '--include-endpoint-owners' '--loglevel')
        
        #Iterating the options available from options array and filling them with the arguments received in order
        iterator=0
        for option in '${{ inputs.scan_name }}' '${{ inputs.traffic_env }}' '${{ inputs.client_scan_token }}' '${{ inputs.plugins }}' '"${{ inputs.include_url_regex }}"' '"${{ inputs.exclude_url_regex }}"' '${{ inputs.target_url }}' '${{ inputs.traceable_server }}' '${{ inputs.scan_timeout }}' '${{ inputs.reference_env }}' '${{ inputs.openapi_spec_ids }}' '${{ inputs.openapi_spec_files }}' '${{ inputs.policy }}' '${{ inputs.include_endpoint_labels}}' '${{ inputs.exclude_endpoint_labels }}' '${{ inputs.include_endpoint_with_owner_attributes }}' '${{ inputs.include_endpoint_owners }}' '${{ inputs.log_level }}'
        do
          if [ -z "$option" ] || [ "$option" = "''" ] || [ "$option" = "NULL" ]
          then
            echo "${optionsArr[$iterator]}" is Null
          else
            scanInitCmd=$scanInitCmd"  "${optionsArr[$iterator]}" "${option}
          fi
          iterator=$(($iterator+1))
        done
        
        $scanInitCmd
      shell: bash
    - name: Run command on cli
      id: run_scan
      if: ${{ inputs.step_name == 'run' }}
      run: |
        export LC_ALL=en_US.utf-8
        export LANG=en_US.utf-8
        if [ -f "/tmp/ca_file.crt" ]
        then
          export TRACEABLE_ROOT_CA_FILE_NAME=/tmp/ca_file.crt
        fi
        if  [ -f "/tmp/ca_cert.crt" ]
        then
          export TRACEABLE_CLI_CERT_FILE_NAME=/tmp/ca_cert.crt
        fi
        if  [ -f "/tmp/ca_key.crt" ]
        then
          export TRACEABLE_CLI_KEY_FILE_NAME=/tmp/ca_key.crt
        fi
        
        traceableCliBinaryLocation=${GITHUB_WORKSPACE}/traceable
        scanRunCmd=$traceableCliBinaryLocation' ast scan run '
        optionsArr=('--token' '--idle-timeout' '--max-retries' '--postman-collection' '--postman-environment')
        
        #Iterating the options available from options array and filling them with the arguments received in order
        iterator=0
        for option in '${{ inputs.client_scan_token }}' '${{ inputs.idle_timeout }}' '${{ inputs.max_retries }}' '${{ inputs.postman_collection }}' '${{ inputs.postman_environment }}' 
        do
          if [ -z "$option" ] || [ "$option" = "''" ] || [ "$option" = "NULL" ]
          then
            echo "${optionsArr[$iterator]}" is Null
          else
            scanRunCmd=$scanRunCmd" "${optionsArr[$iterator]}" "${option}
          fi
          iterator=$(($iterator+1))
        done
        
        $scanRunCmd
      shell: bash
    - name: Publish report
      if: ${{ inputs.step_name == 'run' || inputs.step_name == 'init and run'}}
      run: |
        export LC_ALL=en_US.utf-8
        export LANG=en_US.utf-8
        if [ -f "/tmp/ca_file.crt" ]
        then
          export TRACEABLE_ROOT_CA_FILE_NAME=/tmp/ca_file.crt
        fi
        if  [ -f "/tmp/ca_cert.crt" ]
        then
          export TRACEABLE_CLI_CERT_FILE_NAME=/tmp/ca_cert.crt
        fi
        if  [ -f "/tmp/ca_key.crt" ]
        then
          export TRACEABLE_CLI_KEY_FILE_NAME=/tmp/ca_key.crt
        fi        
        ${GITHUB_WORKSPACE}/traceable ast scan report | sed 1,2d >> $GITHUB_STEP_SUMMARY
      shell: bash
    - name: Stop scan
      id: stop_scan
      if: ${{ inputs.step_name == 'stop' }}
      run: |
        export LC_ALL=en_US.utf-8
        export LANG=en_US.utf-8
        if [ -f "/tmp/ca_file.crt" ]
        then
          export TRACEABLE_ROOT_CA_FILE_NAME=/tmp/ca_file.crt
        fi
        if  [ -f "/tmp/ca_cert.crt" ]
        then
          export TRACEABLE_CLI_CERT_FILE_NAME=/tmp/ca_cert.crt
        fi
        if  [ -f "/tmp/ca_key.crt" ]
        then
          export TRACEABLE_CLI_KEY_FILE_NAME=/tmp/ca_key.crt
        fi        
        ${GITHUB_WORKSPACE}/traceable ast scan stop
      shell: bash