name: Traceable AST Action
description: "Traceable AST Action"
inputs:
  step_name:
    required: true
    description: ''
    default: 'NULL'
  scan_name:
    required: false
    description: ''
    default: 'NULL'
  client_scan_token:
    required: true
    description: ''
    default: 'NULL'
  cli_version:
    required: false
    description: ''
    default: 'latest'
  traffic_env:
    required: true
    description: ''
    default: 'NULL'
  plugins:
    required: false
    description: ''
    default: 'NULL'
  include_url_regex:
    required: false
    description: ''
    default: 'NULL'
  exclude_url_regex:
    required: false
    description: ''
    default: 'NULL'
  target_url:
    required: false
    description: ''
    default: 'NULL'
  traceable_server:
    required: false
    description: ''
    default: 'NULL'
  idle_timeout:
    required: false
    description: ''
    default: 'NULL'
  scan_timeout:
    required: false
    description: ''
    default: 'NULL'
  reference_env:
    required: false
    description: ''
    default: 'NULL'
  max_retries:
    required: false
    description: ''
    default: 'NULL'
  traceable_root_ca:
    required: false
    description: ''
    default: 'NULL'
  traceable_cli_cert:
    required: false
    description: ''
    default: 'NULL'
  traceable_cli_key:
    required: false
    description: ''
    default: 'NULL'

runs:
  using: composite
  steps:
    - name: checkout repo
      uses: actions/checkout@v3
      if: ${{ inputs.step_name == 'init' || inputs.step_name == 'init and run' }}
    - name: Download CLI
      if: ${{ inputs.step_name == 'init' || inputs.step_name == 'init and run' }}
      run: |
        if [[ "$inputs.cli_version" == *"-rc."* ]]; then
          curl https://downloads.traceable.ai/\#cli/rc/${{ inputs.cli_version }}/tars/traceable-cli-${{ inputs.cli_version }}-linux-x86_64.tar.gz -o traceable-cli-${{ inputs.cli_version }}-linux-x86_64.tar.gz 
        fi
        pip install ${GITHUB_WORKSPACE}/traceablecli-0.1.22-py3-none-linux_x86_64.whl --prefix=${GITHUB_WORKSPACE}
      shell: bash
    - name: Init and run command on cli
      if: ${{ inputs.step_name == 'init and run' }}
      run:  |
        chmod +x ${GITHUB_WORKSPACE}/traceable-ast/initAndRun.sh
        ${GITHUB_WORKSPACE}/traceable-ast/initAndRun.sh \
        ${GITHUB_WORKSPACE}/traceable/bin/traceable \
        ${{ inputs.scan_name }} \
        ${{ inputs.traffic_env }} \
        ${{ inputs.client_scan_token }} \
        ${{ inputs.plugins }} \
        ${{ inputs.include_url_regex }} \
        ${{ inputs.exclude_url_regex }} \
        ${{ inputs.target_url }} \
        ${{ inputs.traceable_server }} \
        ${{ inputs.idle_timeout }} \
        ${{ inputs.scan_timeout }} \
        ${{ inputs.reference_env }} \
        ${{ inputs.max_retries }} \
        ${{ inputs.traceable_root_ca }} \
        ${{ inputs.traceable_cli_cert }} \
        ${{ inputs.traceable_cli_key }}
      shell: bash
    - name: Init command on cli
      if: ${{ inputs.step_name == 'init' }}
      run:  |
        chmod +x ${GITHUB_WORKSPACE}/traceable-ast/init.sh
        ${GITHUB_WORKSPACE}/traceable-ast/init.sh \
        ${GITHUB_WORKSPACE}/traceable/bin/traceable \
        ${{ inputs.scan_name }} \
        ${{ inputs.traffic_env }} \
        ${{ inputs.client_scan_token }} \
        ${{ inputs.plugins }} \
        ${{ inputs.include_url_regex }} \
        ${{ inputs.exclude_url_regex }} \
        ${{ inputs.target_url }} \
        ${{ inputs.traceable_server }} \
        ${{ inputs.scan_timeout }} \
        ${{ inputs.reference_env }} \
        ${{ inputs.traceable_root_ca }} \
        ${{ inputs.traceable_cli_cert }} \
        ${{ inputs.traceable_cli_key }}
      shell: bash
    - name: Run command on cli
      id: run_scan
      if: ${{ inputs.step_name == 'run' }}
      run: |
        chmod +x ${GITHUB_WORKSPACE}/traceable-ast/run.sh
        ${GITHUB_WORKSPACE}/traceable-ast/run.sh \
        ${GITHUB_WORKSPACE}/traceable/bin/traceable \
        ${{ inputs.client_scan_token }} \
        ${{ inputs.idle_timeout }} \
        ${{ inputs.max_retries }}
      shell: bash
    - name: Publish report
      if: ${{ inputs.step_name == 'run' || inputs.step_name == 'init and run'}}
      run: |
        ${GITHUB_WORKSPACE}/traceable/bin/traceable ast scan report | sed 1,2d >> $GITHUB_STEP_SUMMARY
      shell: bash

