name: Traceable AST Run
description: "Run action for Traceable AST"
inputs:
  client_scan_token:
    required: true
    description: ''
    default: 'NULL'
  idle_timeout:
    required: false
    description: ''
    default: 'NULL'
  max_retries:
    required: false
    description: ''
    default: 'NULL'

runs:
  using: composite
  steps:
    - name: Run command on cli
      id: run_scan
      run:  |
        chmod +x ${GITHUB_WORKSPACE}/traceable-ast-run/run.sh
        ${GITHUB_WORKSPACE}/traceable-ast-run/run.sh \
        ${GITHUB_WORKSPACE}/traceable/bin/traceable \
        ${{ inputs.client_scan_token }} \
        ${{ inputs.idle_timeout }} \
        ${{ inputs.max_retries }}
      shell: bash
    - name: Publish report summary
      run: |
        ${GITHUB_WORKSPACE}/traceable/bin/traceable ast scan report | sed 1,2d >> $GITHUB_STEP_SUMMARY
      shell: bash