name: Test Traceable AST Init Action And Traceable AST Run Action
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  AstScan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init scan action
        uses: Traceableai/ast-action@main
        with:
          step_name: 'init'
          log_level: 'debug'
          client_scan_token: ${{ secrets.CLIENT_SCAN_TOKEN }}
          traffic_env: 'staging'
          traceable_server: ${{ secrets.TRACEABLE_SERVER }}
          traceable_cli_download_path: https://downloads.traceable.ai/cli/rc/latest/traceable-cli-latest-linux-x86_64.tar.gz
      - name: Run a loop as functional test
        run: |
          for ((i=1;i<=100;i++)); 
          do 
             echo $i
          done
      - name: Run scan action
        uses: Traceableai/ast-action@main
        with:
          step_name: 'run'
          client_scan_token: ${{ secrets.CLIENT_SCAN_TOKEN }}
          traffic_env: 'staging'
          cli_version: 'latest'
      - name: Abort Scan
        uses: Traceableai/ast-action@main
        if: always()
        with:
          step_name: 'stop'
          client_scan_token: ${{ secrets.CLIENT_SCAN_TOKEN_DEMO }}
          traffic_env: 'staging'
          traceable_server: ${{ secrets.TRACEABLE_SERVER_DEMO }}