name: Test Traceable AST Init And Run Action
on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  workflow_dispatch:
    inputs:
     traceable_token:
        description: "traceable_token"
        required: true
     traceable_server:
        description: "traceable_server"
        required: true
jobs:
  InitAndRunAstScan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init and run scan action
        uses: Traceableai/ast-action@main
        with:
          step_name: 'init and run'
          client_scan_token: ${{ github.event.inputs.traceable_token}}
          cli_version: 'latest'
          traceable_server: ${{ github.event.inputs.traceable_server}}
          policy: 'test_open_api'
          include_url_regex: '18.116.165.77'

      - name: Stop Scan
        if: always()
        uses: Traceableai/ast-action@main
        with:
          step_name: 'stop'
          client_scan_token: ${{ github.event.inputs.traceable_token}}
          traffic_env: 'ast_load'
          traceable_server: ${{ github.event.inputs.traceable_server}}
  # functionalTest:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Run a loop as functional test
  #       run: |
  #         for ((i=1;i<=100;i++)); 
  #         do 
  #            echo $i
  #         done
