name: Test Traceable AST Init And Run Action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:name: Test E2E
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  InitAndRunAstScan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init and run scan action
        uses: ./traceable-ast
        with:
          step_name: 'init and run'
          client_scan_token: ${{ secrets.CLIENT_SCAN_TOKEN_DEMO }}
          cli_version: '1.0.0-rc.3'
          traffic_env: 'crapi-demo1'
          traceable_server: ${{ secrets.TRACEABLE_SERVER_DEMO }}
      - name: Stop Scan
        if: always()
        uses: ./traceable-ast
        with:
          step_name: 'stop'
          client_scan_token: ${{ secrets.CLIENT_SCAN_TOKEN_DEMO }}
          traffic_env: 'crapi-demo1'
          traceable_server: ${{ secrets.TRACEABLE_SERVER_DEMO }}
  functionalTest:
    runs-on: ubuntu-20.04
    steps:
      - name: Run a loop as functional test
        run: |
          for ((i=1;i<=100;i++)); 
          do 
             echo $i
          done

  InitAndRunAstScan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init and run scan action
        uses: ./traceable-ast
        with:
          step_name: 'init and run'
          client_scan_token: '65aadb088cb2a508c0c0aea2e51194c4eeabc95ea952a38f094769a067e7e7f2ac884e63f52ab4abc1f9edb691b6b8d7c2654dc5f9027d8d336b0ad7b73ad763'
          cli_version: '1.0.0-rc.3'
          traffic_env: 'astbb3'
          traceable_server: api-dev.traceable.ai
      - name: Stop Scan
        if: always()
        uses: ./traceable-ast
        with:
          step_name: 'stop'
          client_scan_token: '65aadb088cb2a508c0c0aea2e51194c4eeabc95ea952a38f094769a067e7e7f2ac884e63f52ab4abc1f9edb691b6b8d7c2654dc5f9027d8d336b0ad7b73ad763'
          traffic_env: 'astbb3'
          traceable_server: 'api-dev.traceable.ai'
  functionalTest:
    runs-on: ubuntu-20.04
    steps:
      - name: Run a loop as functional test
        run: |
          for ((i=1;i<=100;i++)); 
          do 
             echo $i
          done
