name: Test E2E
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  AstScan:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init scan action
        uses: ./traceable-ast
        with:
          step_name: 'init'
          client_scan_token: 65aadb088cb2a508c0c0aea2e51194c4eeabc95ea952a38f094769a067e7e7f2ac884e63f52ab4abc1f9edb691b6b8d7c2654dc5f9027d8d336b0ad7b73ad763
          traffic_env: 'astbb3'
          traceable_server: api-dev.traceable.ai
      - name: Run a loop as functional test
        run: |
          for ((i=1;i<=100;i++)); 
          do 
             echo $i
          done
      - name: Run scan action
        uses: ./traceable-ast
        with:
          step_name: 'run'
          client_scan_token: 65aadb088cb2a508c0c0aea2e51194c4eeabc95ea952a38f094769a067e7e7f2ac884e63f52ab4abc1f9edb691b6b8d7c2654dc5f9027d8d336b0ad7b73ad763
          traffic_env: 'astbb3'
          cli_version: '1.0.0-rc.3'
      - name: Abort Scan
        uses: ./traceable-ast
        with:
          step_name: 'stop'
          client_scan_token: 65aadb088cb2a508c0c0aea2e51194c4eeabc95ea952a38f094769a067e7e7f2ac884e63f52ab4abc1f9edb691b6b8d7c2654dc5f9027d8d336b0ad7b73ad763
          traffic_env: 'astbb3'
          traceable_server: api-dev.traceable.ai
